üè† [**Inicio**](../../Readme.md) ‚û°Ô∏è / üìñ [**Sesi√≥n 04**](../Readme.md) ‚û°Ô∏è / üìù `Ejemplo 03: Control excepciones`

## üéØ Objetivo

Implementar el manejo de excepciones en Python para escribir programas m√°s seguros y confiables, evitando que se detengan inesperadamente.

---

## üöÄ Comencemos

En lenguajes de programaci√≥n como Python, es com√∫n que los programas se detengan si se encuentra un error. Sin embargo, en muchas ocasiones, es preferible que el programa contin√∫e ejecut√°ndose, incluso si se presenta un error. Para manejar estos casos, Python cuenta con un sistema de excepciones que permite capturar y manejar errores de forma controlada.

---

### üî¶ **Sintaxis b√°sica excepciones**

El manejo de excepciones en Python permite controlar el flujo del programa ante errores o situaciones inesperadas. En lugar de detenerse, el programa puede responder de forma adecuada y continuar operando o cerrar ordenadamente.


<!-- Sintaxis de una excepcion -->
```python
try:
    # Bloque de c√≥digo que puede generar una excepci√≥n
    pass
except Exception as e:
    # Bloque de c√≥digo que se ejecuta si se genera una excepci√≥n
    pass
else:
    # Bloque de c√≥digo que se ejecuta si no se genera una excepci√≥n
    pass
finally:
    # Bloque de c√≥digo que se ejecuta siempre, haya o no excepci√≥n
    pass
```

---

### üõ†Ô∏è **Excepciones mas comunes:**

| N√∫mero | Excepci√≥n             | Descripci√≥n                                                                                      |
|--------|-----------------------|--------------------------------------------------------------------------------------------------|
| 1      | `Exception`           | Clase base para todas las excepciones.                                                           |
| 2      | `ZeroDivisionError`   | Se genera cuando se intenta dividir un n√∫mero por cero.                                          |
| 3      | `ValueError`          | Se genera cuando una funci√≥n recibe un argumento con un valor inapropiado.                       |
| 4      | `TypeError`           | Se genera cuando se intenta realizar una operaci√≥n con un tipo de dato incorrecto.               |
| 5      | `IndexError`          | Se genera cuando se intenta acceder a un √≠ndice fuera de rango en una lista o secuencia.         |
| 6      | `KeyError`            | Se genera cuando se intenta acceder a una clave que no existe en un diccionario.                 |
| 7      | `FileNotFoundError`   | Se genera cuando se intenta abrir un archivo que no existe.                                      |

Son algunas de las excepciones m√°s comunes en Python, pero existen muchas m√°s que se pueden consultar en la [documentaci√≥n oficial](https://docs.python.org/3/library/exceptions.html).

<!-- Vamos a generar algunos errores de acuerdo a la tabla -->
---
### üî¶ **Veamos algunos ejemplos de excepciones:**

1. **Manejo de entrada de datos en un formulario**: Supongamos que un programa necesita obtener un n√∫mero entero del usuario, y es importante que este dato sea v√°lido para continuar con la operaci√≥n.

   ```python
   try:
      edad = int(input("Ingrese su edad: "))
   except ValueError:
      print("La entrada no es un n√∫mero entero v√°lido.")
   else:
      print(f"Edad ingresada: {edad}")
   finally:
      print("Operaci√≥n de ingreso de edad completada.")
   ```

2. **Divisi√≥n segura**: Este c√≥digo realiza una divisi√≥n, pero maneja el caso en que el divisor sea cero, lo cual es un error com√∫n.

   ```python
   try:
      numerador = 10
      denominador = 0
      resultado = numerador / denominador
   except ZeroDivisionError:
      print("No se puede dividir por cero.")
   else:
      print(f"El resultado de la divisi√≥n es {resultado}.")
   finally:
      print("Operaci√≥n de divisi√≥n completada.")
   ```


El uso de la palabra reservada `else` y `finally` no es obligatorio, pero es una buena pr√°ctica incluirlos para asegurarse de que las operaciones se completen correctamente.

---


### üí° **Sab√≠as que...**

En el bloque except, puedes nombrar la excepci√≥n capturada para obtener m√°s informaci√≥n sobre el error. Esto se hace especificando el tipo de excepci√≥n esperado..

```python
try:
    # C√≥digo que puede generar una excepci√≥n
    pass
except ValueError as e:
    # C√≥digo que se ejecuta si se genera una excepci√≥n de tipo ValueError
    print(f"Error de valor: {e}")
except FileNotFoundError as e:
    # C√≥digo que se ejecuta si se genera una excepci√≥n de tipo FileNotFoundError
    print(f"Error de archivo no encontrado: {e}")
```

`Raise` en Python se utiliza para lanzar intencionalmente excepciones, lo que ayuda a gestionar condiciones inesperadas en un programa.


```python
def verificar_edad(edad):
    if edad < 18:
        raise ValueError("Acceso denegado. Debes ser mayor de edad.")
    print("Acceso permitido.")

try:
    verificar_edad(16)
except ValueError as e:
    print(e)
```
---

‚¨ÖÔ∏è [**Anterior**](../Readme.md) | [**Siguiente**](../Reto-02/Readme.md) ‚û°Ô∏è